import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "@/components/providers/SessionProvider";
import { ModalProvider } from "@/components/providers/modals-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();

  return (
    <html lang="en">
      <body suppressHydrationWarning  className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <ModalProvider />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
